# This binary representation has been serialized for easier debugging/patching.
# It will not be used by the program to actually patch anything, so feel free to delete this.

# NOTE: Because of the way TOML treats string literals (single quotes), you cannot escape anything at all, neither backslashes nor single quotes. So in order to be safe, you must use the multiline literals (triple single quotes)! That'll take care of any problems with apostrophes.

[header]
type = '''LcfDataBase'''

#############
# Header 11 #
#############

[[character.1]]
1 = "Kento"
2 = "1337-man"
3 = "new-Tara"
4 = [5]
9 = [0]
15 = "FACE-Kento"
31 = [55,0,1,0,71,0,0,200,0,209,0]
41 = [33]
42 = [29]
51 = [51,0,0,0,159,0,0,0,0,0]
63 = [1,1,2,1,101,0]
67 = "Sorcery"
72 = []
74 = []

#############
# Header 12 #
#############

[[skill.1]]
1 = "---Spezial-Techs---"
8 = [0]
12 = [12]
16 = [1,5,40,79,70,70,41,0]
42 = []
44 = []

#############
# Header 13 #
#############

[[item.1]]
1 = "------>Items"
2 = "Recovers  50  hp"
3 = [0]
5 = [40]
15 = [0]
31 = [0]
33 = [50]
51 = [0]
62 = []
64 = []
66 = []

#############
# Header 14 #
#############

[[enemy.1]]
1 = "TEST"
2 = "DASH_Fledermaus"
4 = [16]
5 = [0]
6 = [12]
7 = [4]
8 = [8]
9 = [8]
11 = [3]
12 = [5]
32 = []
33 = [6]
34 = [2,2,2,2,1,1]
42 = [2,1,1,1,0,2,1,0,5,1,0,0,2,1,1,0,2,1,6,3,1,68,5,1,6,6,1,5,7,1,50,0]

#############
# Header 15 #
#############

[[enemy-group.1]]
1 = "Slimex2"
2 = [2,1,2,2,129,8,3,2,129,5,0,2,2,2,129,56,3,2,129,5,0]
4 = [10]
5 = [1,1,1,1,1,1,1,1,0,0]
11 = [1,1,2,4,1,1,8,0,11,1,20,12,20,206,126,0,5,84,69,115,116,49,0,230,94,0,0,1,0,0,0,0,0,0]

#############
# Header 16 #
#############

[[terrain.1]]
1 = "Normal-"
11 = [0]

#############
# Header 17 #
#############

[[attribute.1]]
1 = "Feuer"
2 = [0]
11 = [129,22]
12 = [125]
14 = [75]
15 = [50]

#############
# Header 18 #
#############

[[condition.1]]
1 = "Tot"
2 = [1]
3 = [5]
4 = [100]
5 = [1]
11 = [80]
12 = [60]
13 = [40]
14 = [20]
51 = " has fallen!"
52 = " collapses!"
55 = " has revived!"

#############
# Header 19 #
#############

[[battle-animation.1]]
1 = "Sound-Test"
6 = [2,1,1,1,1,2,11,1,5,66,108,111,119,50,4,1,90,0,3,1,0,0,2,1,1,1,2,14,1,5,75,105,108,108,56,3,1,90,4,1,110,0,3,1,0,0]
9 = [0]
10 = [2]
12 = [20,1,1,14,1,1,3,2,130,24,4,5,143,255,255,255,120,0,0,2,1,1,0,0,3,1,1,0,0,4,1,1,0,0,5,1,1,0,0,6,1,1,0,0,7,1,1,0,0,8,1,1,0,0,9,1,1,0,0,10,1,1,0,0,11,1,1,0,0,12,1,1,0,0,13,1,1,0,0,14,1,1,0,0,15,1,1,0,0,16,1,1,0,0,17,1,1,0,0,18,1,1,0,0,19,1,1,0,0,20,1,1,0,0]

#############
# Header 20 #
#############

[[chipset.1]]
1 = "World"
2 = "oberwelt"
4 = [0,0,0,0,0,15,0,0,0,0,15,15,15,15,15,0,48,48,0,5,15,15,15,13,15,11,0,15,0]
5 = [31,0,0,0,0,0,0,0,0,0,0,0,0,0,15,0,0,0,0,0,0,0,15,0,0,0,0,0,0]

# No.
#[[vocabulary.1]]
#1 = " emerges!"
#[[system.11]]
#11 = "vehicle"

# No.
#[dictionary]
#vocabulary = [
#	" emerges!", #1
#]
#system = [
#	"vehicle", #11
#]

#############
# Header 21 #
#############

[vocabulary]
1 = " emerges!"

#############
# Header 22 #
#############

[system]
11 = "vehicle"

#############
# Header 23 #
#############

[[switch.1]]
1 = "KAMPF-Ende"

# ...

[[switch.2000]]

#############
# Header 24 #
#############

[[variable.1]]
1 = "Grafik-x"

#############
# Header 25 #
#############

[[event.1]]
1 = "KS_CTB-Leiste V.2.0"
11 = [5]
13 = [45]
commands = [
	[12410,0,"||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||",[]], #0
	[12410,0,"Berechnung optimert nach einer Idee von",[]], #1
	[22410,0,"",[]], #2
	[22410,0,"The_Burrito",[]], #3
	# ...
]
