# Seems to be the same patch format for both database and maps.

# NOTE: Because of the way TOML treats string literals (single quotes), you cannot escape anything at all, neither backslashes nor single quotes. So in order to be safe, you must use the multiline literals (triple single quotes)! That'll take care of any problems with apostrophes.
# Multiline displays are still reserved for dialogue only, as other text never spans multiple lines.

# Only dialogue has the triple single quotes, because it's treated differently (actually spanning multiple commands)
[[dialogue]]
event = 32
page = 3
command = 21
# Explicitly-defined indent for cases where you simply can't infer from the previous indent.
indent = 5
#length = 3 # Redundant if the original is left expanded
# If you want the cleaned up version of either, write a program to extract it.
has_portrait = true
# Convenience field purely for omitting from the overflow report (report.html) when using extractText.
ignore_overflow = true
# Helper field for character name variables (e.g. "\n[1]")
character = '''Kento'''
original = '''
\c[13]Rothaarige Frau\c[0]:\s[6] S...\.Seldan...\.
Glaube mir,\....es ist besser so 
für mich...\.\.\^
'''
# Not used by the program, meant for end user ease-of-use.
# Can't decide between "original-filtered", "filtered", "displayed", etc.
# Then again, do you *really* need this as part of the patch file?
# If you want to utilize the text via copy/paste, wouldn't it be easier to use a quick script to bulk extract all lines so it's easier to work with? You can customize the format too, whether or not newlines are kept intact, etc.
# In that sense, this is a nice to have feature that absolutely should not be the in the patch file itself. You don't want to mess with version control diffs just because.
filtered = '''Rothaarige Frau: S...Seldan... Glaube mir,...es ist besser so für mich...'''
# NOTE: Just in case the original has an empty line (meaning an extra command), it'll display here as an extra newline. Leave that there. Only trim off the first/last newlines (be exact, do NOT use any trim() commands).
patched = '''
\c[13]Red-Haired Woman\c[0]:\s[6] S...\. Seldan...\.
It's...\. better this way...\.\.\^
'''

# (comments go here)
[[dialogue]]
event = 32
page = 3
command = 24
#length = 3 # Redundant if the original is left expanded
has_portrait = true
original = '''
\c[13]Rothaarige Frau\c[0]:\s[6] Diese ewigen 
Kriege,\.... ich kann sie nicht mehr 
sehen...\. Das...\. ständige Kämpfen...\.\.\^
'''
filtered = '''Rothaarige Frau: Diese ewigen Kriege,... ich kann sie nicht mehr sehen... Das... ständige Kämpfen...'''
patched = '''
\c[13]Red-Haired Woman\c[0]:\s[6] This eternal war...\.
I can't bear to see it any longer...\.
These...\. endless battles...\.\.\^
'''

[[other]]
event = 84
page = 1
command = 5
original = '''Auf in die Arena!/Moment, noch nicht!'''
patched = '''All set!/Wait, not yet!'''

# Generic insert function
[[insert]]
event = 1
page = 2
command = 3
index = 3 # Optional specifier for arbitrary operations
patched = '''test-output'''

# Generic replace function
[[replace]]
event = 1
page = 2
command = 3
original = '''test-input'''
patched = '''test-output'''

# Generic delete function
[[delete]]
event = 1
page = 2
command = 3

# ...somehow keep track of the order?

# Add/insert command asks for a command array of arrays `[[1 2 3 4], [...]]`
